BACKEND_URL = "https://dhf-backend-xxxxx-uc.a.run.app"
BACKEND_TOKEN = "change-me"
SERVICE_ACCOUNT_JSON = """{ ... full SA JSON ... }"""
DRIVE_FOLDER_ID = "19udmXqrKypQ7uVRPK5Mdmzo5BNOlG_KQ"
OUTPUT_DIR = "./streamlit_outputs"
